spring.application.name=HumanSoundDetection
spring.datasource.url=jdbc:h2:file:/users/raush/Documents/HumanSound/db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Raushan
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true





